########################################################################
#                                                                      #
# This is the CUPS configuration file.  If you are familiar with       #
# Apache or any of the other popular web servers, we've followed the   #
# same format.  Any configuration variable used here has the same      #
# semantics as the corresponding variable in Apache.  If we need       #
# different functionality then a different name is used to avoid       #
# confusion...                                                         #
#                                                                      #
########################################################################


AccessLog syslog
ErrorLog syslog
LogLevel info
PreserveJobHistory No
PreserveJobFiles No
AutoPurgeJobs Yes
MaxJobs 25
#Printcap /etc/printcap
#PrintcapFormat BSD
#RemoteRoot remroot
# root permissions required to make cups work with the usb backend

HostNameLookups On
KeepAlive On
# No: "BrowseOrder" "BrowseAllow" "BrowseRemoteProtocols"
Browsing Yes
BrowseLocalProtocols DNSSD
DefaultShared Yes
WebInterface Yes

ServerAlias *

<Location />
Order Allow,Deny
Allow all

</Location>

<Location /admin>
AuthType Basic
Require user @SYSTEM
Order Allow,Deny
Allow all

</Location>
Listen *:631
